name: ci
run-name: ${{ github.actor }} go test
on: [push]
jobs:
  gotest:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19'
      - run: go version
      - name: gotest
        run: go test ./... -v -race -coverprofile coverage.out
      - name: codecov upload
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.out
          name: codecov-go
          fail_ci_if_error: true
          verbose: true

